CREATE TABLE food_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    price DOUBLE PRECISION,
    created TIMESTAMP,
    modified TIMESTAMP
);

CREATE TABLE food_menu (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    created TIMESTAMP,
    modified TIMESTAMP
);

CREATE TABLE food_menu_availability_map (
    food_menu_id BIGINT,
    availability VARCHAR(20),
    PRIMARY KEY (food_menu_id, availability),
    FOREIGN KEY (food_menu_id) REFERENCES food_menu(id)
);

CREATE TABLE food_menu_item_map (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    food_menu_id BIGINT,
    food_item_id BIGINT,
    FOREIGN KEY (food_menu_id) REFERENCES food_menu(id),
    FOREIGN KEY (food_item_id) REFERENCES food_item(id)
);

CREATE TABLE food_menu_item_quantity_map (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    food_menu_item_map_id BIGINT,
    quantity INT,
    created TIMESTAMP,
    modified TIMESTAMP,
    FOREIGN KEY (food_menu_item_map_id) REFERENCES food_menu_item_map(id)
);

CREATE TABLE food_order (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT,
    total_cost DOUBLE PRECISION,
    order_status VARCHAR(255),
    created TIMESTAMP,
    modified TIMESTAMP
);

CREATE TABLE order_food_item_quantity_map (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    food_order_id BIGINT,
    food_menu_id BIGINT,
    food_item_id BIGINT,
    quantity INTEGER,
    FOREIGN KEY (food_order_id) REFERENCES food_order(id),
    FOREIGN KEY (food_menu_id) REFERENCES food_menu(id),
    FOREIGN KEY (food_item_id) REFERENCES food_item(id)
);

